### ISSUE TITLE
Enhancement: Username + Enter

### ISSUE THREAD

**Issue by loeffelpan** [Rookiestyle/AlternateAutoType#11]
There are many websites with "devided" login forms. First you have to enter username and press enter and then you have to enter password and press enter. Sometimes this is changing or depending from where you are on that website.

For now i've found a solution by editing the auto-type sequence for the first username form and use the "password + enter" from your plugin for the second form. But sometimes i'm missing the auto-type sequence for the single-form-login with username and password.

Could you please add 
1. The "+ enter"-option for username-only auto-typing from the enhanced auto-type seclection form?
2. Maybe a hotkey for username-only (+ enter) like you did for password-only?

**Comment by loeffelpan** [comment]
Many thanks for that.

**Comment by loeffelpan** [comment]
I just took a closer look to your implementation and maybe found two issues.
1. The labeling (in german and english) is incomplete. Shouldn't it be named _Global auto-type - username only:_ in the third line? Additionally the label for _Username + Enter_ is a tick to high and covers the border of the text field.

![image](https://user-images.githubusercontent.com/34661317/147856055-23fb97da-9dfb-451f-9ff4-b72dc3ea6052.png)

2. Can you please add the _Username = Username + Enter_ in the _Auto-Type Selection form enhancements_? There is the same option for passwords. But not for usernames.

![image](https://user-images.githubusercontent.com/34661317/147856213-9619f82e-3028-4d1a-b7f9-115e74de7307.png)

**Comment by loeffelpan** [comment]
And maybe you would add your hotkey here, like you did with _password-only hotkey_?

![image](https://user-images.githubusercontent.com/34661317/147858534-57057dc3-b27b-43ad-b373-b295802d715e.png)

**Comment by Rookiestyle** [comment]
I'll work on topics 1 and 2.

I won't add the username only hotkey to the KeePass standard options. Didn't do it for password only either.
This screen is served by KeePass and it might change in future releases.
