### ISSUE TITLE
Translation: <Russian>

### ISSUE THREAD

**Issue by ArtyoZ** [Rookiestyle/AlternateAutoType#3]
[NOTE]: # (Please do not forget to attach the translation file)
Language: 
- [ ] New translation
- [x] Update existing translation
- [ ] If updated: Only added missing Texts
- [x] All relevant texts translated

[NOTE]: # (A text is relevant if the standard text in english language is NOT sufficient)
[AlternateAutoType.ru.language.zip](https://github.com/Rookiestyle/AlternateAutoType/files/5738522/AlternateAutoType.ru.language.zip)

**Comment by Rookiestyle** [comment]
Thank you!

**Comment by ArtyoZ** [comment]
Update

[AdvancedAutoType.ru.language.zip](https://github.com/Rookiestyle/AdvancedAutoType/files/12737077/AdvancedAutoType.ru.language.zip)
