### ISSUE TITLE
Alternate hotkey close the autotype selection form almost instantly

### ISSUE THREAD

**Issue by Arthurin** [Rookiestyle/AlternateAutoType#6]
Hello

I installed this plugin this week and didn't manage to make it work correctly. I've multiple entries for the same software and when I use the global autotype everything works fine. But when I try to use the alternate autotype hotkey the autotype form is closed after 0.1sec.

I tried to rollback and install v1.12.1. I also installed .NET framework: 3.5 because I had bigger versions (4, 4.5).

I hope you'll be able to solve this :)

Have a nice day

Here are some logs :
`<?xml version="1.0" encoding="UTF-8"?>

-<DebugInfo>

-<General>

-<Plugin>

<PluginName>AlternateAutoType</PluginName>

<PluginVersion>1.13.0.0</PluginVersion>

</Plugin>

-<DebugTime>

<DebugStart>20210304T100902Z</DebugStart>

<DebugEnd>20210304T180946Z</DebugEnd>

</DebugTime>

<LogLevel>All</LogLevel>

<OS>Windows >= Windows 7 - Microsoft Windows NT 6.1.7601 Service Pack 1</OS>

<DotNet>4.7.3062 (461814)</DotNet>

<KeePass>2.44.0.19625</KeePass>

-<LoadedPlugins>

-<Plugin>

<PluginName>AlternateAutoType.AlternateAutoTypeExt</PluginName>

<PluginVersion>1.13.0.0</PluginVersion>

</Plugin>

-<Plugin>

<PluginName>KeeAnywhere.KeeAnywhereExt</PluginName>

<PluginVersion>1.6.0.0</PluginVersion>

</Plugin>

-<Plugin>

<PluginName>KeePassBrowserImporter.KeePassBrowserImporterExt</PluginName>

<PluginVersion>1.0.9.0</PluginVersion>

</Plugin>

-<Plugin>

<PluginName>YetAnotherFaviconDownloader.YetAnotherFaviconDownloaderExt</PluginName>

<PluginVersion>1.2.4.0</PluginVersion>

</Plugin>

-<Plugin>

<PluginName>CheckPasswordBox.CheckPasswordBoxExt</PluginName>

<PluginVersion>0.2.0.0</PluginVersion>

</Plugin>

-<Plugin>

<PluginName>WebAutoType.WebAutoTypeExt</PluginName>

<PluginVersion>6.3.0.0</PluginVersion>

</Plugin>

</LoadedPlugins>

</General>

-<DebugMessages>

-<DebugEntry>

<Message>Alternate Auto-Type hotkey detected</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180741Z</DateTimeUtc>

-<Parameters>

<Param>Hotkey id: 16477</Param>

<Param>PW only hotkey: 0 - False</Param>

<Param>AAT only hotkey: 16477 - True</Param>

</Parameters>

<StackFrames/>

</DebugEntry>

-<DebugEntry>

<Message>Auto-Type entry selection window added</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180742Z</DateTimeUtc>

<Parameters/>

<StackFrames/>

</DebugEntry>

-<DebugEntry>

<Message>Removed sequences without AAT placeholder</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180742Z</DateTimeUtc>

-<Parameters>

<Param>Before: 3</Param>

<Param>After: 0</Param>

</Parameters>

<StackFrames/>

</DebugEntry>

-<DebugEntry>

<Message>Auto-Type entry selection window shown</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180742Z</DateTimeUtc>

<Parameters/>

<StackFrames/>

</DebugEntry>

-<DebugEntry>

<Message>Auto-Type Entry Selection window closed</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180742Z</DateTimeUtc>

-<Parameters>

<Param>Reason: No entries to display</Param>

</Parameters>

<StackFrames/>

</DebugEntry>

-<DebugEntry>

<Message>Auto-Type entry selection window removed</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180742Z</DateTimeUtc>

<Parameters/>

<StackFrames/>

</DebugEntry>

-<DebugEntry>

<Message>Alternate Auto-Type hotkey detected</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180743Z</DateTimeUtc>

-<Parameters>

<Param>Hotkey id: 16477</Param>

<Param>PW only hotkey: 0 - False</Param>

<Param>AAT only hotkey: 16477 - True</Param>

</Parameters>

<StackFrames/>

</DebugEntry>

-<DebugEntry>

<Message>Auto-Type entry selection window added</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180743Z</DateTimeUtc>

<Parameters/>

<StackFrames/>

</DebugEntry>

-<DebugEntry>

<Message>Removed sequences without AAT placeholder</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180743Z</DateTimeUtc>

-<Parameters>

<Param>Before: 3</Param>

<Param>After: 0</Param>

</Parameters>

<StackFrames/>

</DebugEntry>

-<DebugEntry>

<Message>Auto-Type entry selection window shown</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180743Z</DateTimeUtc>

<Parameters/>

<StackFrames/>

</DebugEntry>

-<DebugEntry>

<Message>Auto-Type Entry Selection window closed</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180743Z</DateTimeUtc>

-<Parameters>

<Param>Reason: No entries to display</Param>

</Parameters>

<StackFrames/>

</DebugEntry>

-<DebugEntry>

<Message>Auto-Type entry selection window removed</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180743Z</DateTimeUtc>

<Parameters/>

<StackFrames/>

</DebugEntry>

-<DebugEntry>

<Message>Adding/Searching m_tabControlRookiestyle</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180748Z</DateTimeUtc>

<Parameters/>

-<StackFrames>

-<StackFrame>

<Method>AddPluginToOptionsForm (PluginTools.Tools)</Method>

<FileName/>

<Line>0</Line>

</StackFrame>

-<StackFrame>

<Method>OnWindowAdded (PluginTools.Tools)</Method>

<FileName/>

<Line>0</Line>

</StackFrame>

-<StackFrame>

<Method>Invoke (System.EventHandler`1)</Method>

<FileName/>

<Line>0</Line>

</StackFrame>

-<StackFrame>

<Method>AddWindow (KeePass.UI.GlobalWindowManager)</Method>

<FileName/>

<Line>0</Line>

</StackFrame>

-<StackFrame>

<Method>OnFormLoad (KeePass.Forms.OptionsForm)</Method>

<FileName/>

<Line>0</Line>

</StackFrame>

</StackFrames>

</DebugEntry>

-<DebugEntry>

<Message>Added m_tabControlRookiestyle</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180748Z</DateTimeUtc>

<Parameters/>

<StackFrames/>

</DebugEntry>

-<DebugEntry>

<Message>AlternateAutoTypeExt tab index : 0 - insert!</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180748Z</DateTimeUtc>

<Parameters/>

<StackFrames/>

</DebugEntry>

-<DebugEntry>

<Message>Added m_tabRookiestyle_PluginOverview</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180748Z</DateTimeUtc>

-<Parameters>

<Param>Listview: 1 /m_tabRookiestyle_PluginOverviewListView</Param>

</Parameters>

<StackFrames/>

</DebugEntry>

-<DebugEntry>

<Message>Checking for KeeTheme</Message>

<Counter>1</Counter>

<Severity>Info</Severity>

<DateTimeUtc>20210304T180748Z</DateTimeUtc>

<Parameters/>

-<StackFrames>

-<StackFrame>

<Method>CheckKeeTheme (PluginTools.Tools)</Method>

<FileName/>

<Line>0</Line>

</StackFrame>

-<StackFrame>

<Method>Invoke (System.EventHandler)</Method>

<FileName/>

<Line>0</Line>

</StackFrame>

-<StackFrame>

<Method>OnShown (System.Windows.Forms.Form)</Method>

<FileName/>

<Line>0</Line>

</StackFrame>

-<StackFrame>

<Method>InvokeMarshaledCallbackHelper (System.Windows.Forms.Control)</Method>

<FileName/>

<Line>0</Line>

</StackFrame>

-<StackFrame>

<Method>RunInternal (System.Threading.ExecutionContext)</Method>

<FileName/>

<Line>0</Line>

</StackFrame>

</StackFrames>

</DebugEntry>

</DebugMessages>

</DebugInfo>`

**Comment by Rookiestyle** [comment]
> sequences without AAT placeholder
Before: 3 After: 0


It seems that the plugin is not able to detect any define alternate autotype sequence. As it can't prevent the auto type selection window from being shown, it closes it since there is nothing to select.

Please share the auto type sequence that you use, it should be something like `{USERNAME}{TAB}{PASSWORD}{ENTER}{AAT}{WhateverOtherValue}{ENTER}`
If this is the case and more than AAT sequences are defined/found, the selection window should be displayed.
If this is the case and.exactly one AAT sequence is.defined/found, this.sequence should be typed automatically.
If this is not the case, the selection window should be closed automatically.

**Comment by Arthurin** [comment]
Oh I didn't understand how the plugin works. I just want to have 2 hotkey to perform the default autotype, so with this new knowledge I overrided the default autotype sequence to have `{USERNAME}{TAB}{PASSWORD}{ENTER}{AAT}{USERNAME}{TAB}{PASSWORD}{ENTER}` and it's perfect, I'll use this plugin to do more tricky stuff in the future ;) 

Thank you for your explanation !

Best regards
